### ISSUE TITLE
LESShat placeholder color

### ISSUE THREAD

**Issue by machal** [rwd-pine/pine#2]
Our version of LESShat is changing page <input placeholder>s to `hotpink` color.

**Comment by Kout** [comment]
Solution? 

> Change default value for first parameter in lesshat.less file.
` .placeholder(@color:hotpink, @element: 08121991) `

[source](https://github.com/madebysource/lesshat/issues/76)

**Comment by machal** [comment]
Fixed here: https://github.com/rwd-pine/pine/pull/3
